import scopeAndMethods from '@published/fengshui/scope-and-methods.json'
import residenceTypesAndScales from '@published/fengshui/residence-types-and-scales.json'
import yinyangElementsTrigramDirections from '@published/fengshui/yinyang-elements-trigram-directions.json'
import formsReadingSequence from '@published/fengshui/forms-reading-sequence.json'
import dragonAndMountainForm from '@published/fengshui/dragon-and-mountain-form.json'
import siteAndMingtang from '@published/fengshui/site-and-mingtang.json'
import sandAndFourEmblems from '@published/fengshui/sand-and-four-emblems.json'
import waterFormAndOutlet from '@published/fengshui/water-form-and-outlet.json'
import compassStructureAndRings from '@published/fengshui/compass-structure-and-rings.json'
import twentyFourMountains from '@published/fengshui/twenty-four-mountains.json'
import sittingAndFacing from '@published/fengshui/sitting-and-facing.json'
import centerlineAdjacentAndBoundaries from '@published/fengshui/centerline-adjacent-and-boundaries.json'
import orientationMeasurementRecord from '@published/fengshui/orientation-measurement-record.json'
import eightMansionsInputSequence from '@published/fengshui/eight-mansions-input-sequence.json'
import houseTrigramGroups from '@published/fengshui/house-trigram-groups.json'
import lifeTrigramGroups from '@published/fengshui/life-trigram-groups.json'
import wanderingStarsDirections from '@published/fengshui/wandering-stars-directions.json'
import doorMainStove from '@published/fengshui/door-main-stove.json'
import xuankongInputSequence from '@published/fengshui/xuankong-input-sequence.json'
import threeYuanNinePeriods from '@published/fengshui/three-yuan-nine-periods.json'
import nineStarFlightPath from '@published/fengshui/nine-star-flight-path.json'
import threeYuanDragonsDirection from '@published/fengshui/three-yuan-dragons-direction.json'
import periodMountainFacingPlates from '@published/fengshui/period-mountain-facing-plates.json'
import purpleWhiteTimeLayers from '@published/fengshui/purple-white-time-layers.json'
import annualPurpleWhite from '@published/fengshui/annual-purple-white.json'
import monthlyPurpleWhite from '@published/fengshui/monthly-purple-white.json'
import dailyPurpleWhite from '@published/fengshui/daily-purple-white.json'
import hourlyPurpleWhite from '@published/fengshui/hourly-purple-white.json'

export const fengshuiDatasets = { scopeAndMethods, residenceTypesAndScales, yinyangElementsTrigramDirections, formsReadingSequence, dragonAndMountainForm, siteAndMingtang, sandAndFourEmblems, waterFormAndOutlet, compassStructureAndRings, twentyFourMountains, sittingAndFacing, centerlineAdjacentAndBoundaries, orientationMeasurementRecord, eightMansionsInputSequence, houseTrigramGroups, lifeTrigramGroups, wanderingStarsDirections, doorMainStove, xuankongInputSequence, threeYuanNinePeriods, nineStarFlightPath, threeYuanDragonsDirection, periodMountainFacingPlates, purpleWhiteTimeLayers, annualPurpleWhite, monthlyPurpleWhite, dailyPurpleWhite, hourlyPurpleWhite }

export const fengshuiIntroductionCard = {
  id:'fengshui-reading-map', group:'从零开始', title:'风水从哪里开始', latin:'Introduction & reading map',
  question:'形势、方位、八宅、玄空与紫白时间层应该按什么顺序理解？',
  summary:'先建立共同空间坐标，再观察形势与环境，随后进入罗盘坐向、八宅和玄空飞星；紫白时间层归入玄空阶段，各层规则分别保存。',
  count:'5 个阶段 · 28 个正式节点', tags:['阅读顺序','五阶段','知识边界'], searchTerms:['风水是什么','风水学习顺序','形势理气'], publicSources:[], status:'专题导读 · 五阶段关系',
}

export const fengshuiCards = [
  fengshuiIntroductionCard,
  {id:'scope-and-methods',group:'共同底座',title:scopeAndMethods.title,latin:'Scope & methods',question:'风水同时观察哪些对象，形势与理气又分别关注什么？',summary:scopeAndMethods.summary,count:'4 层对象 · 2 类方法',tags:['地形水势','空间方位','形势理气'],searchTerms:scopeAndMethods.object_layers.flatMap((x)=>[x.label,...x.items]),publicSources:scopeAndMethods.public_sources,status:'正式范围节点 · 不作现实评价'},
  {id:'residence-types-and-scales',group:'共同底座',title:residenceTypesAndScales.title,latin:'Residence types & scales',question:'墓葬、住宅、建筑和房间为什么不能放在同一尺度判断？',summary:residenceTypesAndScales.summary,count:'2 类对象 · 5 级尺度',tags:['阴宅','阳宅','观察尺度'],searchTerms:residenceTypesAndScales.scales.flatMap((x)=>[x.label,...x.examples]),publicSources:residenceTypesAndScales.public_sources,status:'正式对象节点 · 宅墓分开'},
  {id:'yinyang-elements-trigram-directions',group:'共同底座',title:yinyangElementsTrigramDirections.title,latin:'Directions & nine-palace coordinates',question:'八方、八卦、五行和洛书宫数怎样组成一张九宫坐标？',summary:yinyangElementsTrigramDirections.summary,count:'8 方 · 9 宫 · 5 行',tags:['后天八卦','九宫坐标','五行方位'],searchTerms:[...yinyangElementsTrigramDirections.directions.flatMap((x)=>Object.values(x)),...yinyangElementsTrigramDirections.palaces.flatMap((x)=>Object.values(x))],publicSources:yinyangElementsTrigramDirections.public_sources,status:'正式坐标节点 · 各体系算法分开'},
  {id:'forms-reading-sequence',group:'形势与环境',title:formsReadingSequence.title,latin:'Forms reading sequence',question:'从山水大势走到局部穴场，形势观察按什么顺序展开？',summary:formsReadingSequence.summary,count:'5 步 · 5 类核心关系',tags:['形势','阅读顺序','龙穴砂水'],searchTerms:formsReadingSequence.sequence.flatMap((x)=>[x.label,...x.items]),publicSources:formsReadingSequence.public_sources,status:'正式顺序节点 · 不作吉凶判断'},
  {id:'dragon-and-mountain-form',group:'形势与环境',title:dragonAndMountainForm.title,latin:'Dragon & mountain form',question:'“龙”怎样由远山系统走到祖山、过峡、父母山与入首？',summary:dragonAndMountainForm.summary,count:'4 层观察 · 5 个传统层级',tags:['龙','来龙','山势'],searchTerms:[...dragonAndMountainForm.levels.flatMap((x)=>[x.label,x.focus]),...dragonAndMountainForm.traditional_levels.flatMap((x)=>[x.label,x.focus]),...dragonAndMountainForm.shape_fields],publicSources:dragonAndMountainForm.public_sources,status:'正式形势节点 · 不等同地质构造'},
  {id:'site-and-mingtang',group:'形势与环境',title:siteAndMingtang.title,latin:'Site & mingtang',question:'穴场与明堂怎样组成中心和前方空间？',summary:siteAndMingtang.summary,count:'4 个中心字段 · 3 类明堂',tags:['穴','明堂','观察中心'],searchTerms:[...siteAndMingtang.site_fields.flatMap((x)=>Object.values(x)),...siteAndMingtang.mingtang_layers.flatMap((x)=>Object.values(x))],publicSources:siteAndMingtang.public_sources,status:'正式空间节点 · 尺度分开'},
  {id:'sand-and-four-emblems',group:'形势与环境',title:sandAndFourEmblems.title,latin:'Sand & four emblems',question:'前后左右的砂体怎样组织成玄武、朱雀、青龙、白虎四势？',summary:sandAndFourEmblems.summary,count:'4 势 · 5 类砂体字段',tags:['砂','四势','围护'],searchTerms:[...sandAndFourEmblems.four_emblems.flatMap((x)=>Object.values(x)),...sandAndFourEmblems.sand_fields],publicSources:sandAndFourEmblems.public_sources,status:'正式位置节点 · 四势为相对方位'},
  {id:'water-form-and-outlet',group:'形势与环境',title:waterFormAndOutlet.title,latin:'Water form & outlet',question:'来、过、会、聚、去与水口怎样形成六种可辨水形？',summary:waterFormAndOutlet.summary,count:'6 段水路 · 6 种水形',tags:['水势','水口','来去水'],searchTerms:[...waterFormAndOutlet.water_path.flatMap((x)=>Object.values(x)),...waterFormAndOutlet.shape_fields,...waterFormAndOutlet.shape_patterns.flatMap((x)=>Object.values(x))],publicSources:waterFormAndOutlet.public_sources,status:'正式水势节点 · 不替代水文评估'},
  {id:'compass-structure-and-rings',group:'罗盘与坐向',title:compassStructureAndRings.title,latin:'Basic compass structure & rings',question:'磁针、十字线、二十四山和常见盘层按什么层序读取？',summary:compassStructureAndRings.summary,count:'5 个部件 · 5 层示意',tags:['罗盘','天池','盘层'],searchTerms:[...compassStructureAndRings.components.flatMap((x)=>Object.values(x)),...compassStructureAndRings.representative_ring_order.flatMap((x)=>Object.values(x))],publicSources:compassStructureAndRings.public_sources,status:'正式工具节点 · 盘层用途分开'},
  {id:'twenty-four-mountains',group:'罗盘与坐向',title:twentyFourMountains.title,latin:'Twenty-four mountains',question:'十二地支、八干和四维卦怎样组成二十四个15°方位？',summary:twentyFourMountains.summary,count:'24 山 · 每山 15°',tags:['二十四山','八宫三山','方位度数'],searchTerms:[...twentyFourMountains.mountains.flatMap((x)=>Object.values(x)),...twentyFourMountains.palace_groups.flatMap((x)=>[x.palace,x.direction,...x.mountains])],publicSources:twentyFourMountains.public_sources,status:'正式方位表 · 北0°顺时针'},
  {id:'sitting-and-facing',group:'罗盘与坐向',title:sittingAndFacing.title,latin:'Sitting & facing',question:'坐山和向首为什么必须作为一条180°相反轴线一起记录？',summary:sittingAndFacing.summary,count:'12 组对向 · 4 个轴线字段',tags:['坐山','向首','坐向轴线'],searchTerms:[...sittingAndFacing.opposite_pairs.flat(),...sittingAndFacing.axis_fields.flatMap((x)=>Object.values(x))],publicSources:sittingAndFacing.public_sources,status:'正式轴线节点 · 坐向成对'},
  {id:'centerline-adjacent-and-boundaries',group:'罗盘与坐向',title:centerlineAdjacentAndBoundaries.title,latin:'Centerline & direct/substitute boundaries',question:'正向、兼向、山位分界与下卦替卦应怎样在同一条度数轴上区分？',summary:centerlineAdjacentAndBoundaries.summary,count:'4 个读数 · 2 种排盘方法',tags:['正向','兼向','下卦替卦'],searchTerms:[...centerlineAdjacentAndBoundaries.positions.flatMap((x)=>Object.values(x)),...centerlineAdjacentAndBoundaries.methods.flatMap((x)=>[x.name,...x.aliases,x.input,x.operation]),...centerlineAdjacentAndBoundaries.version_fields],publicSources:centerlineAdjacentAndBoundaries.public_sources,status:'正式边界节点 · 阈值随版本保存'},
  {id:'orientation-measurement-record',group:'罗盘与坐向',title:orientationMeasurementRecord.title,latin:'Orientation measurement record',question:'一次坐向测量至少要留下哪些输入、北基准和误差信息？',summary:orientationMeasurementRecord.summary,count:'6 步 · 8 个记录字段',tags:['测量记录','磁北真北','误差'],searchTerms:[...orientationMeasurementRecord.workflow.flatMap((x)=>Object.values(x)),...orientationMeasurementRecord.record_fields],publicSources:orientationMeasurementRecord.public_sources,status:'正式记录节点 · 不替代专业测绘'},
  {id:'eight-mansions-input-sequence',group:'八宅',title:eightMansionsInputSequence.title,latin:'Eight-mansions input sequence',question:'宅卦、门卦、命卦和游年分别从什么输入得到？',summary:eightMansionsInputSequence.summary,count:'6 步 · 4 类输入',tags:['八宅','输入顺序','版本'],searchTerms:[...eightMansionsInputSequence.workflow.flatMap((x)=>Object.values(x)),...eightMansionsInputSequence.separate_inputs.flatMap((x)=>Object.values(x))],publicSources:eightMansionsInputSequence.public_sources,status:'正式顺序节点 · 输入分开'},
  {id:'house-trigram-groups',group:'八宅',title:houseTrigramGroups.title,latin:'House trigram groups',question:'住宅坐山怎样归入八个宅卦与东西四宅？',summary:houseTrigramGroups.summary,count:'8 宅卦 · 2 组',tags:['宅卦','东四宅','西四宅'],searchTerms:houseTrigramGroups.houses.flatMap((x)=>[x.trigram,x.direction,...x.sitting_mountains,x.facing,x.group]),publicSources:houseTrigramGroups.public_sources,status:'正式宅卦节点 · 坐山定宅'},
  {id:'life-trigram-groups',group:'八宅',title:lifeTrigramGroups.title,latin:'Life trigram groups',question:'古籍三元起例怎样从甲子锚点取得命卦并归入东西四命？',summary:lifeTrigramGroups.summary,count:'9 数 · 3 元 · 1 个固定示例',tags:['命卦','东四命','西四命'],searchTerms:[...lifeTrigramGroups.number_map.flatMap((x)=>Object.values(x)),...lifeTrigramGroups.required_fields,...Object.values(lifeTrigramGroups.fixed_example).flatMap((x)=>typeof x==='object'?Object.values(x):[x])],publicSources:lifeTrigramGroups.public_sources,status:'正式年命节点 · 历史公式分版本'},
  {id:'wandering-stars-directions',group:'八宅',title:wanderingStarsDirections.title,latin:'Wandering stars & directions',question:'以宅卦为伏位时，八颗游年星怎样分布到八个卦宫？',summary:wanderingStarsDirections.summary,count:'8 游星 · 8 宅表',tags:['游年','大游年','八方'],searchTerms:[...wanderingStarsDirections.stars.flatMap((x)=>Object.values(x)),...wanderingStarsDirections.house_tables.flatMap((x)=>Object.values(x))],publicSources:wanderingStarsDirections.public_sources,status:'正式关系表 · 锁定宅卦起伏位'},
  {id:'door-main-stove',group:'八宅',title:doorMainStove.title,latin:'Door, main room & stove',question:'《八宅明镜》与《阳宅三要》怎样分别组织门、主、灶？',summary:doorMainStove.summary,count:'3 个对象 · 2 条方法',tags:['门主灶','阳宅三要','方法比较'],searchTerms:[...doorMainStove.objects.flatMap((x)=>[x.name,x.classical_object,...x.fields]),...doorMainStove.method_comparison.flatMap((x)=>Object.values(x)),...doorMainStove.modern_translation_checks],publicSources:doorMainStove.public_sources,status:'正式比较节点 · 两种方法并列'},
  {id:'xuankong-input-sequence',group:'玄空飞星',title:xuankongInputSequence.title,latin:'Xuan Kong input sequence',question:'从建筑时间和坐向走到三层飞星盘，需要依次确定哪些输入？',summary:xuankongInputSequence.summary,count:'6 步 · 7 项版本字段',tags:['玄空飞星','输入顺序','版本'],searchTerms:[...xuankongInputSequence.workflow.flatMap((x)=>Object.values(x)),...xuankongInputSequence.required_versions],publicSources:xuankongInputSequence.public_sources,status:'正式顺序节点 · 输入与版本分开'},
  {id:'three-yuan-nine-periods',group:'玄空飞星',title:threeYuanNinePeriods.title,latin:'Three cycles & nine periods',question:'一百八十年怎样分成三元九运，各运覆盖哪二十年？',summary:threeYuanNinePeriods.summary,count:'3 元 · 9 运 · 每运 20 年',tags:['三元九运','纪年表','元运'],searchTerms:threeYuanNinePeriods.periods.flatMap((x)=>Object.values(x)),publicSources:threeYuanNinePeriods.public_sources,status:'正式时间表 · 纪年版本明确'},
  {id:'nine-star-flight-path',group:'玄空飞星',title:nineStarFlightPath.title,latin:'Luoshu flight path',question:'一至九怎样沿固定九宫路径顺飞或逆飞？',summary:nineStarFlightPath.summary,count:'9 宫路径 · 2 个方向',tags:['洛书路径','洛书飞布','顺逆飞'],searchTerms:[...nineStarFlightPath.flight_path.flatMap((x)=>Object.values(x)),...nineStarFlightPath.movement.flatMap((x)=>Object.values(x))],publicSources:nineStarFlightPath.public_sources,status:'正式飞布节点 · 星体身份不重复'},
  {id:'three-yuan-dragons-direction',group:'玄空飞星',title:threeYuanDragonsDirection.title,latin:'Three-yuan dragons & flight',question:'二十四山怎样分三元龙，又怎样据此判断山向起星顺逆？',summary:threeYuanDragonsDirection.summary,count:'24 山 · 3 元龙 · 阴阳顺逆',tags:['三元龙','顺飞逆飞','二十四山'],searchTerms:threeYuanDragonsDirection.mountains.flatMap((x)=>Object.values(x)),publicSources:threeYuanDragonsDirection.public_sources,status:'正式顺逆节点 · 下卦基础链'},
  {id:'period-mountain-facing-plates',group:'玄空飞星',title:periodMountainFacingPlates.title,latin:'Period, mountain & facing plates',question:'运盘、山盘和向盘怎样生成，并在固定卯山酉向盘中叠合？',summary:periodMountainFacingPlates.summary,count:'3 层盘 · 1 个九宫示例',tags:['运盘','山盘','向盘'],searchTerms:[...periodMountainFacingPlates.plates.flatMap((x)=>Object.values(x)),...periodMountainFacingPlates.palace_fields,...periodMountainFacingPlates.fixed_chart_example.inputs],publicSources:periodMountainFacingPlates.public_sources,status:'正式三盘节点 · 三层字段分开'},
  {id:'purple-white-time-layers',group:'玄空飞星',title:purpleWhiteTimeLayers.title,latin:'Purple-white time layers',question:'大运、年、月、日、时五种飞星盘怎样分层？',summary:purpleWhiteTimeLayers.summary,count:'5 层时间 · 7 类盘字段',tags:['紫白飞星','时间层','盘层'],searchTerms:[...purpleWhiteTimeLayers.layers.flatMap((x)=>Object.values(x)),...purpleWhiteTimeLayers.separate_fields],publicSources:purpleWhiteTimeLayers.public_sources,status:'正式总序节点 · 各层公式分开'},
  {id:'annual-purple-white',group:'玄空飞星',title:annualPurpleWhite.title,latin:'Annual purple-white stars',question:'三元甲子怎样确定每年的入中星？',summary:annualPurpleWhite.summary,count:'3 个锚点 · 4 年校验序列',tags:['年紫白','值年星','三元甲子'],searchTerms:[...annualPurpleWhite.yuan_anchors.flatMap((x)=>Object.values(x)),...annualPurpleWhite.fixed_sequence.flatMap((x)=>Object.values(x))],publicSources:annualPurpleWhite.public_sources,status:'正式年序节点 · 年界分版本'},
  {id:'monthly-purple-white',group:'玄空飞星',title:monthlyPurpleWhite.title,latin:'Monthly purple-white stars',question:'年支三组怎样决定正月起星和十二个月序列？',summary:monthlyPurpleWhite.summary,count:'3 组年支 · 12 月序列',tags:['月紫白','年支分组','月界'],searchTerms:[...monthlyPurpleWhite.year_branch_groups.flatMap((x)=>[x.group,...x.branches,x.first_month_name]),...monthlyPurpleWhite.version_fields],publicSources:monthlyPurpleWhite.public_sources,status:'正式月序节点 · 月界分版本'},
  {id:'daily-purple-white',group:'玄空飞星',title:dailyPurpleWhite.title,latin:'Daily purple-white stars',question:'六个节气段怎样给日紫白设置甲子锚点与顺逆？',summary:dailyPurpleWhite.summary,count:'6 段 · 1 个固定日序',tags:['日紫白','节气段','甲子日'],searchTerms:[...dailyPurpleWhite.segments.flatMap((x)=>Object.values(x)),...dailyPurpleWhite.fixed_day_sequence.days.flatMap((x)=>Object.values(x))],publicSources:dailyPurpleWhite.public_sources,status:'具名版本节点 · 不接入实时日期'},
  {id:'hourly-purple-white',group:'玄空飞星',title:hourlyPurpleWhite.title,latin:'Hourly purple-white stars',question:'冬夏至半周、日支分组和十二时支怎样共同决定时星？',summary:hourlyPurpleWhite.summary,count:'3 组日支 · 6 条时序',tags:['时紫白','冬夏至','时支'],searchTerms:[...hourlyPurpleWhite.day_branch_groups.flatMap((x)=>Object.values(x).flat?.()||Object.values(x)),...hourlyPurpleWhite.hour_order],publicSources:hourlyPurpleWhite.public_sources,status:'具名版本节点 · 不接入实时时间'},
]

export const fengshuiLearningStages = [
  {id:'foundation',label:'共同底座',note:'研究范围、宅墓尺度、八卦方位与九宫坐标',cardIds:['scope-and-methods','residence-types-and-scales','yinyang-elements-trigram-directions'],status:'基础坐标'},
  {id:'forms',label:'形势与环境',note:'形势总序、龙与山势、穴与明堂、砂与四势、水势与水口',cardIds:['forms-reading-sequence','dragon-and-mountain-form','site-and-mingtang','sand-and-four-emblems','water-form-and-outlet'],status:'环境关系'},
  {id:'compass',label:'罗盘与坐向',note:'罗盘结构、二十四山、坐向轴线、正替边界与测量记录',cardIds:['compass-structure-and-rings','twenty-four-mountains','sitting-and-facing','centerline-adjacent-and-boundaries','orientation-measurement-record'],status:'方位工具'},
  {id:'eight-mansions',label:'八宅',note:'输入顺序、宅卦、命卦、八游星与门主灶',cardIds:['eight-mansions-input-sequence','house-trigram-groups','life-trigram-groups','wandering-stars-directions','door-main-stove'],status:'八宅关系'},
  {id:'flying-stars',label:'玄空飞星',note:'输入、三元九运、洛书飞布、三元龙、三层盘，以及年、月、日、时紫白',cardIds:['xuankong-input-sequence','three-yuan-nine-periods','nine-star-flight-path','three-yuan-dragons-direction','period-mountain-facing-plates','purple-white-time-layers','annual-purple-white','monthly-purple-white','daily-purple-white','hourly-purple-white'],status:'宅盘与时间层'},
]
